int32 BEHAVIOR_UNKNOWN=0
int32 BEHAVIOR_STANDING=1
int32 BEHAVIOR_APPROACHING=2
int32 BEHAVIOR_SHOOTING=3
int32 BEHAVIOR_AIMING=4

int32 WEAPON_UNKNOWN=0
int32 WEAPON_NONE=1
int32 WEAPON_GUN=2
int32 WEAPON_KNIFE=3

int32 JOB_UNKNOWN=0
int32 JOB_CIVILIAN=1
int32 JOB_SOLDIER=2

int32 track_id
int32 class_id
string class_name
float32 score
float32 x1
float32 y1
float32 x2
float32 y2
int32 behavior
int32 weapon
int32 job
string result_json
float32 inference_time_ms
float32 image_sync_delta_sec
